# Generated by Django 5.0 on 2023-12-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_titles_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behaviors',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='categorys',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='emotions',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='feelings',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='thinkings',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='delete',
        ),
    ]
